### ISSUE TITLE
  It would be better if it can generate MESSAGE_HANDLER  code

### ISSUE THREAD

**Issue by DreamerL** [FlatGlobus/WTLBuilder#3]
NICE PROJECT ABSOLUTELY!!!  It would be better if it can generate MESSAGE_HANDLER  code, Like MFC, WTL,  double-click the control will automatic generation MESSAGE_HANDLER  code， of course, this is optional for users. generate MESSAGE_HANDLER  code or not.  Manually adding MESSAGE_HANDLER to each control is tedious if the Form have many controls,  You can close this issue at any time, because it's my suggest not a issue actually

**Comment by FlatGlobus** [comment]
I've tried to implement that and I wrote some code but.. I had no time to accomplish this work. Maybe I'll implement it.
